---
defaultChannel: tech-preview-v1
icon:
  base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZmlsbD0iIzNFOEVFRCIgZD0iTTEyIDFhMTEgMTEgMCAxIDAgMTEgMTFBMTEgMTEgMCAwIDAgMTIgMXptMCAyMGE5IDkgMCAxIDEgOS05IDkgOSAwIDAgMS05IDl6bTUtMTNoLTN2LTJhMiAyIDAgMCAwLTQgMHYySDdhMSAxIDAgMCAwLTEgMXY3YTEgMSAwIDAgMCAxIDFoMTBhMSAxIDAgMCAwIDEtMXYtN2ExIDEgMCAwIDAtMS0xem0tNS0yYTEgMSAwIDAgMSAxIDF2Mkg5di0yYTEgMSAwIDAgMSAxLTF6bTQgMTBIOHYtNWg4eiIvPjwvc3ZnPg==
  mediatype: image/svg+xml
name: ocp-secrets-management-operator
schema: olm.package
