FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.26 AS builder

# Values for below ARGs will be passed from tekton configs for konflux builds.
## Release version of the ocp-secrets-management-operator source code used in the build.
ARG RELEASE_VERSION
## Commit hash that considered for the image build.
ARG COMMIT_SHA
## GitHub URL of the ocp-secrets-management-operator source repository.
ARG SOURCE_URL
## The location where the source code is stored.
ARG SOURCE_DIR="/go/src/github.com/openshift/ocp-secrets-management-operator"

WORKDIR $SOURCE_DIR
# This monorepo keeps the operator source under operator/ (with the
# `operator-build` target living in the repo's root Makefile), unlike a
# standalone operator repo where the source would sit at the repo root.
COPY . .
COPY LICENSE /licenses/

RUN make operator-build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/ocp-secrets-management-operator"

COPY --from=builder $SOURCE_DIR/operator/bin/manager /bin/ocp-secrets-management-operator
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="ocp-secrets-management-operator-container" \
      cpe="cpe:/a:redhat:secrets_management_console:0.1::el9" \
      name="secrets-management-operator/ocp-secrets-management-operator-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="ocp-secrets-management-operator" \
      maintainer="Red Hat, Inc." \
      description="ocp-secrets-management-operator-container" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      distribution-scope="public" \
      url="${SOURCE_URL}" \
      io.openshift.expose-services="" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.openshift.maintainer.product="OpenShift Container Platform" \
      io.openshift.tags="data,images,operator,ocp-secrets-management,secrets-management-operator" \
      io.k8s.display-name="openshift-secrets-management-operator" \
      io.k8s.description="ocp-secrets-management-operator-container"

ENTRYPOINT ["/bin/ocp-secrets-management-operator"]
